### PR TITLE
App Localization: Integrating Seven Different Languages for the ScreenStream App

### LINKED ISSUE #258: Translation Feature: Add translated data in strings.xml file.
### Hello @dkrivoruchko,

**I'm interested in contributing to the translation. Could you please provide me with the names of the languages you are looking to translate into?**

### PR DESCRIPTION
**Pull request by SB2318**
Hello @dkrivoruchko,

I hope you are doing well!

As I have shown my interest in the locale addition for your application, I have submitted a pull request **(PR)** that adds support for seven different locales to each submodule of your application.

Please review my PR and provide any feedback or modifications that you think are necessary. 
I'm looking forward to your input to make the application accessible to a wider audience.

Thank you!

Fixes #258

### CODE REVIEW

**Comment by dkrivoruchko** [comment]
Great job!
Will check later in details. 

Small comment: strings that have `translatable="false"` like 
`<string name="app_name" translatable="false">ScreenStream</string>` 
should NOT be translated. Please update PR.

**Comment by SB2318** [comment]
Okay, Thanks for your feedback. 😊
And Looking forward for your response.

**Comment by dkrivoruchko** [comment]
Thank you for your efforts.
I merged it and fixed small issues.
Also found some missing translations for `string-array` values like:
https://github.com/dkrivoruchko/ScreenStream/blob/1a9e69a3195472b485f8789177e293e555fe12be/mjpeg/src/main/res/values/strings.xml#L71
or
https://github.com/dkrivoruchko/ScreenStream/blob/1a9e69a3195472b485f8789177e293e555fe12be/app/src/main/res/values/strings.xml#L49

Will be nice to have them translated also.

**Comment by dkrivoruchko** [comment]
Btw, there is a server repo for WebRTC mode.
Fill free to help with them also 
https://github.com/dkrivoruchko/ScreenStreamWeb/tree/main/src/client/static/lang

**Comment by SB2318** [comment]
> Btw, there is a server repo for WebRTC mode. Fill free to help with them also https://github.com/dkrivoruchko/ScreenStreamWeb/tree/main/src/client/static/lang

Sure! 🎉 Happy to contribute! 😊 And thanks for considering the previous contribution. 👍

**Pull request merged**
